### ISSUE TITLE
AST viewer does not work with codeql/ruby-all 0.50

### ISSUE THREAD

**Issue by anticomputer** [anticomputer/emacs-codeql#5]
Something started breaking in the switch from 0.4.x to 0.5.0 and the AST viewer templated query runs receive:

```
The query depends on an extensional predicate sinkModel which has not been defined.
```

Need to investigate what has changed in how the templated AST queries are used in the Ruby libraries.

**Comment by anticomputer** [comment]
Looks like it's due to the inclusion of model.yml in:

```
λ ruby-all/0.5.0 › cat qlpack.yml 
---
library: true
name: codeql/ruby-all
version: 0.5.0
buildMetadata:
  sha: 5317fb5b53ebed638c86e02e3bb5f479cb7cba07
  cliVersion: 2.12.0
dependencies:
  codeql/regex: 0.0.4
  codeql/ssa: 0.0.8
  codeql/tutorial: 0.0.1
dbscheme: ruby.dbscheme
extractor: ruby
upgrades: upgrades
groups:
 - ruby
dataExtensions:
 - codeql/ruby/frameworks/**/model.yml
λ ruby-all/0.5.0 ›
```
It seems like the model libraries never end up in any search path for the query server or something along those lines. They are not resolved as party of the library paths. Need to dig a bit more.
